language: python
env:
 - DJANGO=1.7
 - DJANGO=1.8
 - DJANGO=1.9
python:
 - "2.7"
 - "3.4"
 - "pypy"
 - "pypy3"
install:
 - pip install -U pip
 - pip install -r requirements.txt

 # metlog-py doesn't support Python 3
 - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r optional.txt; fi

 - pip install "Django<${DJANGO}"
script: DJANGO_SETTINGS_MODULE='django_statsd.test_settings' nosetests
